/*
 * PDP FSP API (Implementation Friendly Version)
 * DRAFT FOR INTERNAL REVIEW ONLY - Based on API Definition.docx updated on 2017-07-06 - Implementation friendly version. [Changes from pervious version (2.7) - maxLength changed to 48 from 32 for IlpCondition and IlpFulfilment Types.]
 *
 * OpenAPI spec version: 2.8
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ilp.conditions.models.pdp;

import java.util.Objects;

/**
 * PUT /authorizations/{ID} object
 */
public class AuthorizationsIDPutResponse {

  private String authenticationInfo = null;

  private String responseType = null;

  public AuthorizationsIDPutResponse authenticationInfo(String authenticationInfo) {
    this.authenticationInfo = authenticationInfo;
    return this;
  }

   /**
   * OTP or QR Code if entered, otherwise empty.
   * @return authenticationInfo
  **/
  public String getAuthenticationInfo() {
    return authenticationInfo;
  }

  public void setAuthenticationInfo(String authenticationInfo) {
    this.authenticationInfo = authenticationInfo;
  }

  public AuthorizationsIDPutResponse responseType(String responseType) {
    this.responseType = responseType;
    return this;
  }

   /**
   * Enum containing response information; if the customer entered the authentication value, rejected the transaction, or requested a resend of the authentication value.
   * @return responseType
  **/
  public String getResponseType() {
    return responseType;
  }

  public void setResponseType(String responseType) {
    this.responseType = responseType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthorizationsIDPutResponse authorizationsIDPutResponse = (AuthorizationsIDPutResponse) o;
    return Objects.equals(this.authenticationInfo, authorizationsIDPutResponse.authenticationInfo) &&
        Objects.equals(this.responseType, authorizationsIDPutResponse.responseType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(authenticationInfo, responseType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuthorizationsIDPutResponse {\n");
    
    sb.append("    authenticationInfo: ").append(toIndentedString(authenticationInfo)).append("\n");
    sb.append("    responseType: ").append(toIndentedString(responseType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}
