/*
 * PDP FSP API (Implementation Friendly Version)
 * DRAFT FOR INTERNAL REVIEW ONLY - Based on API Definition.docx updated on 2017-07-06 - Implementation friendly version. [Changes from pervious version (2.7) - maxLength changed to 48 from 32 for IlpCondition and IlpFulfilment Types.]
 *
 * OpenAPI spec version: 2.8
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ilp.conditions.models.pdp;

import java.util.Objects;
import java.util.ArrayList;
import java.util.List;

/**
 * POST /bulkQuotes object
 */
public class BulkQuotesPostRequest {

  private String bulkQuoteId = null;

  private Party payer = null;

  private GeoCode geoCode = null;

  private String expiration = null;

  private List<IndividualQuote> individualQuotes = new ArrayList<IndividualQuote>();

  private ExtensionList extensionList = null;

  public BulkQuotesPostRequest bulkQuoteId(String bulkQuoteId) {
    this.bulkQuoteId = bulkQuoteId;
    return this;
  }

   /**
   * Common ID between the FSPs for the bulk quote object, decided by the Payer FSP. The ID should be reused for resends of the same bulk quote. A new ID should be generated for each new bulk quote.
   * @return bulkQuoteId
  **/
  public String getBulkQuoteId() {
    return bulkQuoteId;
  }

  public void setBulkQuoteId(String bulkQuoteId) {
    this.bulkQuoteId = bulkQuoteId;
  }

  public BulkQuotesPostRequest payer(Party payer) {
    this.payer = payer;
    return this;
  }

   /**
   * Get payer
   * @return payer
  **/
  public Party getPayer() {
    return payer;
  }

  public void setPayer(Party payer) {
    this.payer = payer;
  }

  public BulkQuotesPostRequest geoCode(GeoCode geoCode) {
    this.geoCode = geoCode;
    return this;
  }

   /**
   * Get geoCode
   * @return geoCode
  **/
  public GeoCode getGeoCode() {
    return geoCode;
  }

  public void setGeoCode(GeoCode geoCode) {
    this.geoCode = geoCode;
  }

  public BulkQuotesPostRequest expiration(String expiration) {
    this.expiration = expiration;
    return this;
  }

   /**
   * Expiration is optional to let the Payee FSP know when a quote no longer needs to be returned.
   * @return expiration
  **/
  public String getExpiration() {
    return expiration;
  }

  public void setExpiration(String expiration) {
    this.expiration = expiration;
  }

  public BulkQuotesPostRequest individualQuotes(List<IndividualQuote> individualQuotes) {
    this.individualQuotes = individualQuotes;
    return this;
  }

  public BulkQuotesPostRequest addIndividualQuotesItem(IndividualQuote individualQuotesItem) {
    this.individualQuotes.add(individualQuotesItem);
    return this;
  }

   /**
   * List of quotes elements.
   * @return individualQuotes
  **/
  public List<IndividualQuote> getIndividualQuotes() {
    return individualQuotes;
  }

  public void setIndividualQuotes(List<IndividualQuote> individualQuotes) {
    this.individualQuotes = individualQuotes;
  }

  public BulkQuotesPostRequest extensionList(ExtensionList extensionList) {
    this.extensionList = extensionList;
    return this;
  }

   /**
   * Get extensionList
   * @return extensionList
  **/
  public ExtensionList getExtensionList() {
    return extensionList;
  }

  public void setExtensionList(ExtensionList extensionList) {
    this.extensionList = extensionList;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BulkQuotesPostRequest bulkQuotesPostRequest = (BulkQuotesPostRequest) o;
    return Objects.equals(this.bulkQuoteId, bulkQuotesPostRequest.bulkQuoteId) &&
        Objects.equals(this.payer, bulkQuotesPostRequest.payer) &&
        Objects.equals(this.geoCode, bulkQuotesPostRequest.geoCode) &&
        Objects.equals(this.expiration, bulkQuotesPostRequest.expiration) &&
        Objects.equals(this.individualQuotes, bulkQuotesPostRequest.individualQuotes) &&
        Objects.equals(this.extensionList, bulkQuotesPostRequest.extensionList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bulkQuoteId, payer, geoCode, expiration, individualQuotes, extensionList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BulkQuotesPostRequest {\n");
    
    sb.append("    bulkQuoteId: ").append(toIndentedString(bulkQuoteId)).append("\n");
    sb.append("    payer: ").append(toIndentedString(payer)).append("\n");
    sb.append("    geoCode: ").append(toIndentedString(geoCode)).append("\n");
    sb.append("    expiration: ").append(toIndentedString(expiration)).append("\n");
    sb.append("    individualQuotes: ").append(toIndentedString(individualQuotes)).append("\n");
    sb.append("    extensionList: ").append(toIndentedString(extensionList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}
