/*
 * PDP FSP API (Implementation Friendly Version)
 * DRAFT FOR INTERNAL REVIEW ONLY - Based on API Definition.docx updated on 2017-07-06 - Implementation friendly version. [Changes from pervious version (2.7) - maxLength changed to 48 from 32 for IlpCondition and IlpFulfilment Types.]
 *
 * OpenAPI spec version: 2.8
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ilp.conditions.models.pdp;

import java.util.Objects;

/**
 * Data model for the complex type IndividualTransfer.
 */
public class IndividualTransfer {

  private String transferId = null;

  private Money transferAmount = null;

  private String ilpPacket = null;

  private String condition = null;

  private ExtensionList extensionList = null;

  public IndividualTransfer transferId(String transferId) {
    this.transferId = transferId;
    return this;
  }

   /**
   * Identifies messages related to the same /transfers sequence.
   * @return transferId
  **/
  public String getTransferId() {
    return transferId;
  }

  public void setTransferId(String transferId) {
    this.transferId = transferId;
  }

  public IndividualTransfer transferAmount(Money transferAmount) {
    this.transferAmount = transferAmount;
    return this;
  }

   /**
   * Get transferAmount
   * @return transferAmount
  **/
  public Money getTransferAmount() {
    return transferAmount;
  }

  public void setTransferAmount(Money transferAmount) {
    this.transferAmount = transferAmount;
  }

  public IndividualTransfer ilpPacket(String ilpPacket) {
    this.ilpPacket = ilpPacket;
    return this;
  }

   /**
   * ILP Packet containing the amount delivered to the Payee and the ILP Address of the Payee and any other end-to-end data.
   * @return ilpPacket
  **/
  public String getIlpPacket() {
    return ilpPacket;
  }

  public void setIlpPacket(String ilpPacket) {
    this.ilpPacket = ilpPacket;
  }

  public IndividualTransfer condition(String condition) {
    this.condition = condition;
    return this;
  }

   /**
   * Condition that must be fulfilled to commit the transfer.
   * @return condition
  **/
  public String getCondition() {
    return condition;
  }

  public void setCondition(String condition) {
    this.condition = condition;
  }

  public IndividualTransfer extensionList(ExtensionList extensionList) {
    this.extensionList = extensionList;
    return this;
  }

   /**
   * Get extensionList
   * @return extensionList
  **/
  public ExtensionList getExtensionList() {
    return extensionList;
  }

  public void setExtensionList(ExtensionList extensionList) {
    this.extensionList = extensionList;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IndividualTransfer individualTransfer = (IndividualTransfer) o;
    return Objects.equals(this.transferId, individualTransfer.transferId) &&
        Objects.equals(this.transferAmount, individualTransfer.transferAmount) &&
        Objects.equals(this.ilpPacket, individualTransfer.ilpPacket) &&
        Objects.equals(this.condition, individualTransfer.condition) &&
        Objects.equals(this.extensionList, individualTransfer.extensionList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transferId, transferAmount, ilpPacket, condition, extensionList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IndividualTransfer {\n");
    
    sb.append("    transferId: ").append(toIndentedString(transferId)).append("\n");
    sb.append("    transferAmount: ").append(toIndentedString(transferAmount)).append("\n");
    sb.append("    ilpPacket: ").append(toIndentedString(ilpPacket)).append("\n");
    sb.append("    condition: ").append(toIndentedString(condition)).append("\n");
    sb.append("    extensionList: ").append(toIndentedString(extensionList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}
