/*
 * PDP FSP API (Implementation Friendly Version)
 * DRAFT FOR INTERNAL REVIEW ONLY - Based on API Definition.docx updated on 2017-07-06 - Implementation friendly version. [Changes from pervious version (2.7) - maxLength changed to 48 from 32 for IlpCondition and IlpFulfilment Types.]
 *
 * OpenAPI spec version: 2.8
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ilp.conditions.models.pdp;

import java.util.Objects;
import java.util.ArrayList;
import java.util.List;

/**
 * PUT /participants/{ID} object
 */
public class ParticipantsIDPutResponse {

  private List<PartyResult> partyList = new ArrayList<PartyResult>();

  private String currency = null;

  public ParticipantsIDPutResponse partyList(List<PartyResult> partyList) {
    this.partyList = partyList;
    return this;
  }

  public ParticipantsIDPutResponse addPartyListItem(PartyResult partyListItem) {
    this.partyList.add(partyListItem);
    return this;
  }

   /**
   * List of PartyResult elements that were either created or failed to be created.
   * @return partyList
  **/
  public List<PartyResult> getPartyList() {
    return partyList;
  }

  public void setPartyList(List<PartyResult> partyList) {
    this.partyList = partyList;
  }

  public ParticipantsIDPutResponse currency(String currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Indicate that the provided Currency was set to be supported by each successfully added PartyIdInfo.
   * @return currency
  **/
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ParticipantsIDPutResponse participantsIDPutResponse = (ParticipantsIDPutResponse) o;
    return Objects.equals(this.partyList, participantsIDPutResponse.partyList) &&
        Objects.equals(this.currency, participantsIDPutResponse.currency);
  }

  @Override
  public int hashCode() {
    return Objects.hash(partyList, currency);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ParticipantsIDPutResponse {\n");

    sb.append("    partyList: ").append(toIndentedString(partyList)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
