/*
 * PDP FSP API (Implementation Friendly Version)
 * DRAFT FOR INTERNAL REVIEW ONLY - Based on API Definition.docx updated on 2017-07-06 - Implementation friendly version. [Changes from pervious version (2.7) - maxLength changed to 48 from 32 for IlpCondition and IlpFulfilment Types.]
 *
 * OpenAPI spec version: 2.8
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ilp.conditions.models.pdp;

import java.util.Objects;

/**
 * Data model for the complex type PartyIdInfo.
 */
public class PartyIdInfo {

  private String partyIdType = null;

  private String partyIdentifier = null;

  private String partySubIdOrType = null;

  private String fspId = null;

  public PartyIdInfo partyIdType(String partyIdType) {
    this.partyIdType = partyIdType;
    return this;
  }

   /**
   * Type of the identifier.
   * @return partyIdType
  **/
  public String getPartyIdType() {
    return partyIdType;
  }

  public void setPartyIdType(String partyIdType) {
    this.partyIdType = partyIdType;
  }

  public PartyIdInfo partyIdentifier(String partyIdentifier) {
    this.partyIdentifier = partyIdentifier;
    return this;
  }

   /**
   * An identifier for the Party.
   * @return partyIdentifier
  **/
  public String getPartyIdentifier() {
    return partyIdentifier;
  }

  public void setPartyIdentifier(String partyIdentifier) {
    this.partyIdentifier = partyIdentifier;
  }

  public PartyIdInfo partySubIdOrType(String partySubIdOrType) {
    this.partySubIdOrType = partySubIdOrType;
    return this;
  }

   /**
   * A sub-identifier or sub-type for the Party.
   * @return partySubIdOrType
  **/
  public String getPartySubIdOrType() {
    return partySubIdOrType;
  }

  public void setPartySubIdOrType(String partySubIdOrType) {
    this.partySubIdOrType = partySubIdOrType;
  }

  public PartyIdInfo fspId(String fspId) {
    this.fspId = fspId;
    return this;
  }

   /**
   * FSP ID (if known)
   * @return fspId
  **/
  public String getFspId() {
    return fspId;
  }

  public void setFspId(String fspId) {
    this.fspId = fspId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PartyIdInfo partyIdInfo = (PartyIdInfo) o;
    return Objects.equals(this.partyIdType, partyIdInfo.partyIdType) &&
        Objects.equals(this.partyIdentifier, partyIdInfo.partyIdentifier) &&
        Objects.equals(this.partySubIdOrType, partyIdInfo.partySubIdOrType) &&
        Objects.equals(this.fspId, partyIdInfo.fspId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(partyIdType, partyIdentifier, partySubIdOrType, fspId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PartyIdInfo {\n");
    
    sb.append("    partyIdType: ").append(toIndentedString(partyIdType)).append("\n");
    sb.append("    partyIdentifier: ").append(toIndentedString(partyIdentifier)).append("\n");
    sb.append("    partySubIdOrType: ").append(toIndentedString(partySubIdOrType)).append("\n");
    sb.append("    fspId: ").append(toIndentedString(fspId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}
