/*
 * PDP FSP API (Implementation Friendly Version)
 * DRAFT FOR INTERNAL REVIEW ONLY - Based on API Definition.docx updated on 2017-07-06 - Implementation friendly version. [Changes from pervious version (2.7) - maxLength changed to 48 from 32 for IlpCondition and IlpFulfilment Types.]
 *
 * OpenAPI spec version: 2.8
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ilp.conditions.models.pdp;

import java.util.Objects;
import java.util.ArrayList;
import java.util.List;

/**
 * POST /participants object
 */
public class ParticipantsPostRequest {

  private String requestId = null;

  private List<PartyIdInfo> partyList = new ArrayList<PartyIdInfo>();

  private String currency = null;

  public ParticipantsPostRequest requestId(String requestId) {
    this.requestId = requestId;
    return this;
  }

   /**
   * The ID of the request, decided by the client. Used for identification of the callback from the server.
   * @return requestId
  **/
  public String getRequestId() {
    return requestId;
  }

  public void setRequestId(String requestId) {
    this.requestId = requestId;
  }

  public ParticipantsPostRequest partyList(List<PartyIdInfo> partyList) {
    this.partyList = partyList;
    return this;
  }

  public ParticipantsPostRequest addPartyListItem(PartyIdInfo partyListItem) {
    this.partyList.add(partyListItem);
    return this;
  }

   /**
   * List of PartyIdInfo elements that the client would like to update or create FSP information about.
   * @return partyList
  **/
  public List<PartyIdInfo> getPartyList() {
    return partyList;
  }

  public void setPartyList(List<PartyIdInfo> partyList) {
    this.partyList = partyList;
  }

  public ParticipantsPostRequest currency(String currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Indicate that the provided Currency is supported by each PartyIdInfo in the list.
   * @return currency
  **/
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ParticipantsPostRequest participantsPostRequest = (ParticipantsPostRequest) o;
    return Objects.equals(this.requestId, participantsPostRequest.requestId) &&
        Objects.equals(this.partyList, participantsPostRequest.partyList) &&
        Objects.equals(this.currency, participantsPostRequest.currency);
  }

  @Override
  public int hashCode() {
    return Objects.hash(requestId, partyList, currency);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ParticipantsPostRequest {\n");
    
    sb.append("    requestId: ").append(toIndentedString(requestId)).append("\n");
    sb.append("    partyList: ").append(toIndentedString(partyList)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}
