/*
 * PDP FSP API (Implementation Friendly Version)
 * DRAFT FOR INTERNAL REVIEW ONLY - Based on API Definition.docx updated on 2017-07-06 - Implementation friendly version. [Changes from pervious version (2.7) - maxLength changed to 48 from 32 for IlpCondition and IlpFulfilment Types.]
 *
 * OpenAPI spec version: 2.8
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ilp.conditions.models.pdp;

import java.util.Objects;

/**
 * Data model for the complex type PartyPersonalInfo.
 */
public class PartyPersonalInfo {

  private PartyComplexName complexName = null;

  private String dateOfBirth = null;

  public PartyPersonalInfo complexName(PartyComplexName complexName) {
    this.complexName = complexName;
    return this;
  }

   /**
   * Get complexName
   * @return complexName
  **/
  public PartyComplexName getComplexName() {
    return complexName;
  }

  public void setComplexName(PartyComplexName complexName) {
    this.complexName = complexName;
  }

  public PartyPersonalInfo dateOfBirth(String dateOfBirth) {
    this.dateOfBirth = dateOfBirth;
    return this;
  }

   /**
   * Date of birth for the Party.
   * @return dateOfBirth
  **/
  public String getDateOfBirth() {
    return dateOfBirth;
  }

  public void setDateOfBirth(String dateOfBirth) {
    this.dateOfBirth = dateOfBirth;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PartyPersonalInfo partyPersonalInfo = (PartyPersonalInfo) o;
    return Objects.equals(this.complexName, partyPersonalInfo.complexName) &&
        Objects.equals(this.dateOfBirth, partyPersonalInfo.dateOfBirth);
  }

  @Override
  public int hashCode() {
    return Objects.hash(complexName, dateOfBirth);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PartyPersonalInfo {\n");
    
    sb.append("    complexName: ").append(toIndentedString(complexName)).append("\n");
    sb.append("    dateOfBirth: ").append(toIndentedString(dateOfBirth)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}
