/*
 * PDP FSP API (Implementation Friendly Version)
 * DRAFT FOR INTERNAL REVIEW ONLY - Based on API Definition.docx updated on 2017-07-06 - Implementation friendly version. [Changes from pervious version (2.7) - maxLength changed to 48 from 32 for IlpCondition and IlpFulfilment Types.]
 *
 * OpenAPI spec version: 2.8
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ilp.conditions.models.pdp;

import java.util.Objects;

/**
 * PUT /quotes/{ID} object
 */
public class QuotesIDPutResponse {

  private Money payeeFspReceiveAmount = null;

  private Money payeeReceiveAmount = null;

  private Money payeeFspFee = null;

  private Money payeeFspCommission = null;

  private String expiration = null;

  private GeoCode geoCode = null;

  private String ilpPacket = null;

  private String condition = null;

  private ExtensionList extensionList = null;

  public QuotesIDPutResponse payeeFspReceiveAmount(Money payeeFspReceiveAmount) {
    this.payeeFspReceiveAmount = payeeFspReceiveAmount;
    return this;
  }

   /**
   * Get payeeFspReceiveAmount
   * @return payeeFspReceiveAmount
  **/
  public Money getPayeeFspReceiveAmount() {
    return payeeFspReceiveAmount;
  }

  public void setPayeeFspReceiveAmount(Money payeeFspReceiveAmount) {
    this.payeeFspReceiveAmount = payeeFspReceiveAmount;
  }

  public QuotesIDPutResponse payeeReceiveAmount(Money payeeReceiveAmount) {
    this.payeeReceiveAmount = payeeReceiveAmount;
    return this;
  }

   /**
   * Get payeeReceiveAmount
   * @return payeeReceiveAmount
  **/
  public Money getPayeeReceiveAmount() {
    return payeeReceiveAmount;
  }

  public void setPayeeReceiveAmount(Money payeeReceiveAmount) {
    this.payeeReceiveAmount = payeeReceiveAmount;
  }

  public QuotesIDPutResponse payeeFspFee(Money payeeFspFee) {
    this.payeeFspFee = payeeFspFee;
    return this;
  }

   /**
   * Get payeeFspFee
   * @return payeeFspFee
  **/
  public Money getPayeeFspFee() {
    return payeeFspFee;
  }

  public void setPayeeFspFee(Money payeeFspFee) {
    this.payeeFspFee = payeeFspFee;
  }

  public QuotesIDPutResponse payeeFspCommission(Money payeeFspCommission) {
    this.payeeFspCommission = payeeFspCommission;
    return this;
  }

   /**
   * Get payeeFspCommission
   * @return payeeFspCommission
  **/
  public Money getPayeeFspCommission() {
    return payeeFspCommission;
  }

  public void setPayeeFspCommission(Money payeeFspCommission) {
    this.payeeFspCommission = payeeFspCommission;
  }

  public QuotesIDPutResponse expiration(String expiration) {
    this.expiration = expiration;
    return this;
  }

   /**
   * Date and time until when the quotation is valid and can be honored when used in the subsequent transaction.
   * @return expiration
  **/
  public String getExpiration() {
    return expiration;
  }

  public void setExpiration(String expiration) {
    this.expiration = expiration;
  }

  public QuotesIDPutResponse geoCode(GeoCode geoCode) {
    this.geoCode = geoCode;
    return this;
  }

   /**
   * Get geoCode
   * @return geoCode
  **/
  public GeoCode getGeoCode() {
    return geoCode;
  }

  public void setGeoCode(GeoCode geoCode) {
    this.geoCode = geoCode;
  }

  public QuotesIDPutResponse ilpPacket(String ilpPacket) {
    this.ilpPacket = ilpPacket;
    return this;
  }

   /**
   * The ILP Packet that must be attached to the transfer by the Payer.
   * @return ilpPacket
  **/
  public String getIlpPacket() {
    return ilpPacket;
  }

  public void setIlpPacket(String ilpPacket) {
    this.ilpPacket = ilpPacket;
  }

  public QuotesIDPutResponse condition(String condition) {
    this.condition = condition;
    return this;
  }

   /**
   * The condition that must be attached to the transfer by the Payer.
   * @return condition
  **/
  public String getCondition() {
    return condition;
  }

  public void setCondition(String condition) {
    this.condition = condition;
  }

  public QuotesIDPutResponse extensionList(ExtensionList extensionList) {
    this.extensionList = extensionList;
    return this;
  }

   /**
   * Get extensionList
   * @return extensionList
  **/
  public ExtensionList getExtensionList() {
    return extensionList;
  }

  public void setExtensionList(ExtensionList extensionList) {
    this.extensionList = extensionList;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QuotesIDPutResponse quotesIDPutResponse = (QuotesIDPutResponse) o;
    return Objects.equals(this.payeeFspReceiveAmount, quotesIDPutResponse.payeeFspReceiveAmount) &&
        Objects.equals(this.payeeReceiveAmount, quotesIDPutResponse.payeeReceiveAmount) &&
        Objects.equals(this.payeeFspFee, quotesIDPutResponse.payeeFspFee) &&
        Objects.equals(this.payeeFspCommission, quotesIDPutResponse.payeeFspCommission) &&
        Objects.equals(this.expiration, quotesIDPutResponse.expiration) &&
        Objects.equals(this.geoCode, quotesIDPutResponse.geoCode) &&
        Objects.equals(this.ilpPacket, quotesIDPutResponse.ilpPacket) &&
        Objects.equals(this.condition, quotesIDPutResponse.condition) &&
        Objects.equals(this.extensionList, quotesIDPutResponse.extensionList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(payeeFspReceiveAmount, payeeReceiveAmount, payeeFspFee, payeeFspCommission, expiration, geoCode, ilpPacket, condition, extensionList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QuotesIDPutResponse {\n");
    
    sb.append("    payeeFspReceiveAmount: ").append(toIndentedString(payeeFspReceiveAmount)).append("\n");
    sb.append("    payeeReceiveAmount: ").append(toIndentedString(payeeReceiveAmount)).append("\n");
    sb.append("    payeeFspFee: ").append(toIndentedString(payeeFspFee)).append("\n");
    sb.append("    payeeFspCommission: ").append(toIndentedString(payeeFspCommission)).append("\n");
    sb.append("    expiration: ").append(toIndentedString(expiration)).append("\n");
    sb.append("    geoCode: ").append(toIndentedString(geoCode)).append("\n");
    sb.append("    ilpPacket: ").append(toIndentedString(ilpPacket)).append("\n");
    sb.append("    condition: ").append(toIndentedString(condition)).append("\n");
    sb.append("    extensionList: ").append(toIndentedString(extensionList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}
