/*
 * PDP FSP API (Implementation Friendly Version)
 * DRAFT FOR INTERNAL REVIEW ONLY - Based on API Definition.docx updated on 2017-07-06 - Implementation friendly version. [Changes from pervious version (2.7) - maxLength changed to 48 from 32 for IlpCondition and IlpFulfilment Types.]
 *
 * OpenAPI spec version: 2.8
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ilp.conditions.models.pdp;

import java.util.Objects;

/**
 * PUT /transactionRequests/{ID} object
 */
public class TransactionRequestsIDPutResponse {

  private String transactionId = null;

  private String transactionRequestState = null;

  private ExtensionList extensionList = null;

  public TransactionRequestsIDPutResponse transactionId(String transactionId) {
    this.transactionId = transactionId;
    return this;
  }

   /**
   * Identifies a related transaction (if a transaction has been created).
   * @return transactionId
  **/
  public String getTransactionId() {
    return transactionId;
  }

  public void setTransactionId(String transactionId) {
    this.transactionId = transactionId;
  }

  public TransactionRequestsIDPutResponse transactionRequestState(String transactionRequestState) {
    this.transactionRequestState = transactionRequestState;
    return this;
  }

   /**
   * State of the transaction request.
   * @return transactionRequestState
  **/
  public String getTransactionRequestState() {
    return transactionRequestState;
  }

  public void setTransactionRequestState(String transactionRequestState) {
    this.transactionRequestState = transactionRequestState;
  }

  public TransactionRequestsIDPutResponse extensionList(ExtensionList extensionList) {
    this.extensionList = extensionList;
    return this;
  }

   /**
   * Get extensionList
   * @return extensionList
  **/
  public ExtensionList getExtensionList() {
    return extensionList;
  }

  public void setExtensionList(ExtensionList extensionList) {
    this.extensionList = extensionList;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransactionRequestsIDPutResponse transactionRequestsIDPutResponse = (TransactionRequestsIDPutResponse) o;
    return Objects.equals(this.transactionId, transactionRequestsIDPutResponse.transactionId) &&
        Objects.equals(this.transactionRequestState, transactionRequestsIDPutResponse.transactionRequestState) &&
        Objects.equals(this.extensionList, transactionRequestsIDPutResponse.extensionList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transactionId, transactionRequestState, extensionList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransactionRequestsIDPutResponse {\n");
    
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("    transactionRequestState: ").append(toIndentedString(transactionRequestState)).append("\n");
    sb.append("    extensionList: ").append(toIndentedString(extensionList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}
